=== Editor's Note

8/28/2018

This post is about a user asking about which pool has the lowest transaction fee. Maxwell speaks in support of Eligius, a pool ran by Luke-Jr.

'''

=== So which pool has the least transaction fees?

*clonedone*: Ever since deepbit rose to 550 G/Hash, I've been getting a little less coins due to the fact that my rig isn't all that crazy.
Is there another pool that has little to no fees and lets me cash out instantly like deepbit does?
Eligus feels strange since you dont make an account there and every thing is paid instantly. I'd like to see how much I would make in a day ya know?


{empty} +
*nster*: Deepbit takes 3%, but pays you for invalid BLOCKS (not shares obviously) and has long polling as well. Considering that, slush's 2% fee is act
ually HIGHER because long polling + invalid blocks combined is more than 1% better.

And as I have said, I don't trust Bitcoinpool at all so Deepbit is really the best.

You can add an askrate to phoenix if that bothers you btw.

{empty} +
*Maxwell*: 0_o

Eligius (https://en.bitcoin.it/wiki/Eligius) charges something like 0.00015% now.

Eligius has no accounts or passwords to be compromised.

Eligius pays users out of the generated transaction directly, no funny business with money handling.

Eligius supports long polling.  For me, I get lower half the stales from Eligius than I got from deepbit (this might be because eligius is 20ms from me
 while deepbit is 110ms from me).

Eligius is run by Luke-Jr^1^, who is obviously competent, and who is usually around on IRC.

I'm not saying you're a fool for not using Eligius, but I'm not saying you aren't one either. ;)


~1.~ ~Luke~ ~Jr.~ ~is~ ~a~ ~Bitcoin~ ~Core~ ~developer.~